// code by jph
package ch.ethz.idsc.sophus.filter;

import ch.ethz.idsc.sophus.curve.BezierFunction;
import ch.ethz.idsc.sophus.math.GeodesicInterface;
import ch.ethz.idsc.tensor.RationalScalar;
import ch.ethz.idsc.tensor.Tensor;
import ch.ethz.idsc.tensor.opt.TensorUnaryOperator;

/** extrapolation by evaluating the Bezier curve defined by n number of
 * control points at parameter value n / (n - 1)
 * 
 * The weight mask is generated by the following formula
 * <pre>
 * With[{p = n / (n - 1)}, Table[(1 - p)^(n - k - 1) p^k, {k, 0, n - 1}]]
 * </pre>
 * 
 * The leading coefficient converges to
 * <pre>
 * Limit[(n/(n - 1))^(n - 1), n -> Infinity] == Exp[1]
 * </pre> */
public class BezierExtrapolation implements TensorUnaryOperator {
  /** @param geodesicInterface
   * @return */
  public static TensorUnaryOperator of(GeodesicInterface geodesicInterface) {
    return new BezierExtrapolation(geodesicInterface);
  }

  // ---
  private final GeodesicInterface geodesicInterface;

  private BezierExtrapolation(GeodesicInterface geodesicInterface) {
    this.geodesicInterface = geodesicInterface;
  }

  @Override // from TensorUnaryOperator
  public Tensor apply(Tensor tensor) {
    int n = tensor.length();
    return BezierFunction.of(geodesicInterface, tensor).apply(RationalScalar.of(n, n - 1));
  }
}
