// code by jph
package ch.ethz.idsc.owl.math.sample;

import ch.ethz.idsc.tensor.Tensor;
import ch.ethz.idsc.tensor.Tensors;

/** inspired by
 * <a href="https://reference.wolfram.com/language/ref/RandomSample.html">RandomSample</a> */
public enum RandomSample {
  ;
  /** @param randomSampleInterface
   * @return single random sample generated by given randomSampleInterface */
  public static Tensor of(RandomSampleInterface randomSampleInterface) {
    return randomSampleInterface.randomSample();
  }

  /** @param randomSampleInterface
   * @param length
   * @return length number of random samples generated by given randomSampleInterface */
  public static Tensor of(RandomSampleInterface randomSampleInterface, int length) {
    return Tensors.vector(i -> randomSampleInterface.randomSample(), length);
  }
}
